### ISSUE TITLE
Web Map not appearing

### ISSUE THREAD

**Issue by SUPERN00Bthefirst** [SakuraSedaia/Songs-of-War-Dev-Repo#7]
The web map will not show if the site is running in https
if you reload the site in http the web map appears

**Comment by SUPERN00Bthefirst** [comment]
It cant be fixed on our end, its an issue with dynmap, it doesn't support HTTPS yet.

**Comment by SakuraSedaia** [comment]
I fixed the issue, the problem was the URL the Webmap Element was pulling from was using HTTP and not HTTPS
